### ISSUE TITLE
StrongVPN no available account in MacOS

### ISSUE THREAD

**Issue by zzylol** [vpncn/vpncn.github.io#100]
您好，我付费了StrongVPN并且成功。但是在登录客户端的时候显示no available account. 我更换了一个客户端就可以登录。但是登录之后，无论哪个结点都显示：The VPN server did not respond.
请问要怎么办

**Comment by vpncn** [comment]
客户端现在只能使用V1.65的精简客户端，找客服获取并开通OpenVPN账号就行了，和客服说你在中国不能连接，客服会帮你搞定。官网首页右下角有在线帮助，或者 进入用户后台页面提交ticket信。

**Comment by zzylol** [comment]
谢谢，客服帮我搞定了。
