### ISSUE TITLE
StrongVPN：Suspicious activity detected, please contact the support

### ISSUE THREAD

**Issue by WangElsie** [vpncn/vpncn.github.io#101]
Suspicious activity detected, please contact the support

购买的时候要填邮箱，提示邮箱有问题，无法购买

**Comment by vpncn** [comment]
系统应该是检测到了可以活动。建议使用本地网络访问（文章有方法）或者换个邮箱试试。

**Comment by WangElsie** [comment]
邮件联系了客服，把IP发给他们，客服帮我处理了
