### ISSUE TITLE
strong vpn国内网站慢

### ISSUE THREAD

**Issue by tutuzhu98** [vpncn/vpncn.github.io#107]
请问有什么办法解决吗

**Comment by vpncn** [comment]
StrongVPN是全局代理，连接后相当于是你的访问指令发送到国外的服务器，国外的服务器接受国内网站的数据，再把数据传送给你，这样绕路太长，肯定比你直接访问国内网站要慢。解决办法是Vmware安装虚拟机，本机不用任何代理，访问国内网站，虚拟机进行翻墙，虚拟机和本机的文件可以共享或拖拽传输的。
