### ISSUE TITLE
请问有没有在linux上合适的vpn？

### ISSUE THREAD

**Issue by acacxhm7** [vpncn/vpncn.github.io#11]
如题。我购买了express，但是在树莓派上的连接十分不稳定，大部分时间都是连不上的，连上也很容易断线。

**Comment by vpncn** [comment]
建议连接LA-5和marina bay节点，我现在用这2个。最近敏感期，墙的干扰增强了，VPN目前都是这样，掉线和速度都不如之前，等过一段时间应该会恢复正常。
