### ISSUE TITLE
连接错误

### ISSUE THREAD

**Issue by tutuzhu98** [vpncn/vpncn.github.io#110]
![QQ截图20210720104439](https://user-images.githubusercontent.com/86200055/126466438-b3f90ca6-2b54-443e-b8b8-5590c56ac7ee.png)
请问为什么经常出现这个问题？

**Comment by vpncn** [comment]
哪款VPN？用的什么客户端版本？

如果是StrongVPN建议使用精简版客户端，找客服获取，使用方法文中有。

**Comment by tutuzhu98** [comment]
strong vpn ，而且是精简版。

**Comment by tutuzhu98** [comment]
> 哪款VPN？用的什么客户端版本？
> 
> 如果是StrongVPN建议使用精简版客户端，找客服获取，使用方法文中有。

strong vpn ，而且是精简版。

**Comment by vpncn** [comment]
换节点试一下（文中有列出），用TCP协议。如果都不行就申请退款吧。

**Comment by tutuzhu98** [comment]
这是什么原因啊？是我电脑的问题吗？

**Comment by vpncn** [comment]
电脑系统设置或者网络的问题，我刚才试了，有些节点还是可以连的。

**Comment by tutuzhu98** [comment]
跟host文件有关系吗？我之前因为登不了strongvpn网站把原host文件删了下了那个新的。

**Comment by vpncn** [comment]
> 跟host文件有关系吗？我之前因为登不了strongvpn网站把原host文件删了下了那个新的。

和这个没有关系，可以联系技术客服帮你看看。
