### ISSUE TITLE
StrongVPN众多节点无法连接

### ISSUE THREAD

**Issue by ming-lx** [vpncn/vpncn.github.io#114]
最近StrongVPN啥情况啊，能用的节点好像只有欧洲部分极个别可以，其他的好像都连接不上了，是我操作的问题嘛

**Comment by vpncn** [comment]
我刚刚测试了6个节点，5个能连。应该是你的操作问题，按这个方法：点击客户端上的Change Location，在弹出的窗口选择By server（Manual）手动选择服务器，选择国家->城市->连接协议（Open），选择下方服务器，然后点击Next，之后转换服务器(Switch)就行了。
我刚测试的6个服务器状态（连接协议OpenVPN）：
Germany Frankfurt str-fra302 可用
Spain Madrid 301 可用
Spain Madrid 302 连接一次失败
UK Manchester 303  可用
France Paris 301  可用
Italy Milan 303 可用
