### ISSUE TITLE
Bitz Net怎么样子？

### ISSUE THREAD

**Issue by liangzilixueha** [vpncn/vpncn.github.io#115]
我看没有介绍这篇文章的话

**Comment by vpncn** [comment]
我看了一下，这个几乎没什么客户，去年刚出来的国产App，安全性存疑，另外使用的话别买长期套餐，因为随时有跑路的风险。

**Comment by liangzilixueha** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [vpncn/vpncn.github.io] Bitz Net怎么样子？ (#115)





 
Closed #115.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
