### ISSUE TITLE
StrongVpn Host文件无法下载

### ISSUE THREAD

**Issue by Ghost-Luu** [vpncn/vpncn.github.io#118]
StrongVpn Host文件无法下载，只有一个节点可以正常连接，其它所有节点都是在connecting，人麻了

**Comment by vpncn** [comment]
我前天晚上都用过，能连的节点不少，看下文中线路选择方法，估计是操作方法问题。

**Comment by Ghost-Luu** [comment]
大佬们指教下Host文件怎么修改，我咨询下客服。   文档上链接打不开了。

**Comment by Ghost-Luu** [comment]
Host文件已下载。
