### ISSUE TITLE
nordvpn就是个坑啊

### ISSUE THREAD

**Issue by elicec** [vpncn/vpncn.github.io#134]

**Comment by elicec** [comment]
刚开始试用了一个月还好。后来果断买了个三年的套餐。。然后用了没几个月，各种连不上，各种找客服，客户各种给我发中国定制版的客户端。各种没用啊。。。又不能退款。现在已经不用了

**Comment by vpncn** [comment]
现在Nordvpn找客服要的手动配置还能用，网速也还行。不过nord我用的很少。
