### ISSUE TITLE
ExpressVPN银联支付后没有收到邮件

### ISSUE THREAD

**Issue by Dyqsc** [vpncn/vpncn.github.io#150]
我在ExpressVPN银联支付后没有收到包含ExpressVPN账号和临时密码的邮件

**Comment by Dyqsc** [comment]
是境外支付到账需要很久还是其他什么原因？问了客服，目前没有查到相关的信息

**Comment by vpncn** [comment]
一般都是付完款就自动发送邮件的。

付款后有没有自动返回到官网？咨询客服处理一下

**Comment by Dyqsc** [comment]
不知道什么情况，客服目前也查不到我的订阅
