### ISSUE TITLE
Alipay interface failured in the StrongVPN

### ISSUE THREAD

**Issue by 1274248407** [vpncn/vpncn.github.io#152]
ERROR CODE ILLEGAL_PARTNER

**Comment by 1274248407** [comment]
![explorer_2lLDiAdG6v](https://user-images.githubusercontent.com/80159393/152100834-01f2583e-30f8-4e97-b8e8-fa4e523c82b4.png)
![explorer_yvbLsm7SQ4](https://user-images.githubusercontent.com/80159393/152100880-e323b76a-81c2-4429-b842-47c70f3044d0.png)

**Comment by vpncn** [comment]
进用户后台支付，文中有提示。
