### ISSUE TITLE
StrongVPN 挂了

### ISSUE THREAD

**Issue by BinarySky10** [vpncn/vpncn.github.io#159]
坐标帝都, 最近这两天Strong VPN挂了

**Comment by vpncn** [comment]
并没有，使用精简版客户端吧，我一直连韩国-Seoul和德国-frankfurt等几个线路好好的。通用版的有时会遇到你说的这种情况。

**Comment by wh-isper** [comment]
> 并没有，使用精简版客户端吧，我一直连韩国-Seoul和德国-frankfurt等几个线路好好的。通用版的有时会遇到你说的这种情况。

电脑可以用，但iphone连不上
