### ISSUE TITLE
iphone连不上StrongVPN

### ISSUE THREAD

**Issue by wh-isper** [vpncn/vpncn.github.io#160]
之前用的好好的，这几天突然连不上了，电脑windows可以连的上

**Comment by vpncn** [comment]
找客服，会给你具体的配置方法。iphone版本是这样的，遇到大封锁要过一段时间才能恢复。

**Comment by wh-isper** [comment]
> 找客服，会给你具体的配置方法。iphone版本是这样的，遇到大封锁要过一段时间才能恢复。

  好的，谢啦！
