### ISSUE TITLE
购买 vpn 是使用 paypel 支付安全些，还是使用alipay ... 银联 支付好  （bitcoin除外）

### ISSUE THREAD

**Issue by zy-uu** [vpncn/vpncn.github.io#164]
主要担心用银联买vpn的会不会被 探测到 ......
但是我感觉paypel好像也一样 ，毕竟也是绑卡 ， 但这个感觉好像多了一层（i dont know）

**Comment by vpncn** [comment]
最好PayPal，其次银联卡和alipay。PayPal余额支付不存在这个问题，PayPal绑卡（非余额）支付和银联卡、alipay支付，如果检查起来这些都有可能，但金额不大、数量不多的境外支付一般也不会管你了。
