### ISSUE TITLE
垃圾strongvpn, 大家千万别用！！

### ISSUE THREAD

**Issue by Jason-LY18** [vpncn/vpncn.github.io#173]
自从上个月开始，就基本上无法用了。修了半天给了个可以连接的方案，但是几乎一分钟掉3次，最高网速在20k/s，咨询客服，居然找我要去年的支付宝记录来验证用户（去年哪知道会出现这种事，记录都没有保存），给不了记录就回我一个自求多福，真是垃圾到家了。之前他们家和expressvpn相比就是价格优势和live help，自从上个月开始，真的是武功全废，啥都不灵了。

**Comment by YanLu-nyu** [comment]
![Screenshot 2022-04-09 224717](https://user-images.githubusercontent.com/10672549/162599061-4b45dc8e-686a-4621-9c4b-856bdc2999b4.jpg)
