### ISSUE TITLE
expressvpn最近一周出现问题无法使用了

### ISSUE THREAD

**Issue by habaohaba** [vpncn/vpncn.github.io#204]
真的绝了，心情很难受。以为expressvpn可以靠谱一点，选择了这么贵的vpn，但是还是出现了问题，而且出现了问题没有任何处理办法，只能够干等。联系了客服，客服也说是有问题，正在解决，唉，上个网这么难，心累。

**Comment by vpncn** [comment]
是的，用什么VPN都会出问题的，express算很好的了，能一直挺到现在。很多VPN被封一次1-2年都不换线路IP，在国内无法使用。

**Comment by tiancaipipi110** [comment]
这两天还有哪个vpn能用啊？expressvpn被封十天了，估计这次被封的比较狠
