### ISSUE TITLE
用了一年strong到期了，想换别的，有啥推荐吗？

### ISSUE THREAD

**Issue by MainByElse** [vpncn/vpncn.github.io#214]
strong用了一年，马上要续期了，第二年太贵，加上感觉网速偏慢，连接时间过长，App时不时挂掉，使用感觉不佳，需要手动配置；优点是客服确实到位，随时都能找到

目前看了Express，太贵，pass
同事用了几年的蓝灯，感觉没出过大问题，唯一的问题是iOS上App也挺拉胯，各位有什么好的推荐吗？

**Comment by XuZelin2001** [comment]
PIA，或者privatevpn 都是两刀每月，中国都不错

**Comment by XuZelin2001** [comment]
最便宜的话买个Fastestvpn，16.6美元终身：
官方购买链接： https://fastestvpn.com/lifetime-special-deal 

促销码：SPECIAL2021  折后16.6美元

**Comment by XuZelin2001** [comment]
@MainByElse https://playbeasts.com/question/2374 完整版可以看这个

**Comment by GoForLunch** [comment]
PIA现在还能用吗？还是又换了别的vpn？

**Comment by Biyougong831** [comment]
PIA去年国庆之后客户端直连就挂了。不过他官方提供了socks代理，可以作为openvpn前置代理使用，这样能连。
