### ISSUE TITLE
windows精简版的安装过程下载不了 .NET Framework 2.0 Service Pack 2

### ISSUE THREAD

**Issue by misterwu1998** [vpncn/vpncn.github.io#220]
![image](https://user-images.githubusercontent.com/59677175/189578927-c3f7606c-7f4a-4f09-b9ed-e9871f2aed71.png)

**Comment by beanjoy** [comment]
直接百度下就行。

**Comment by zhaodesen** [comment]
https://www.microsoft.com/zh-CN/download/details.aspx?id=22

**Comment by alexlii1971** [comment]
请点击这里，也许可以帮到你：

https://github.com/alexlii1971/ChinaVPN/blob/main/README.md

**Comment by misterwu1998** [comment]
已在StrongVPN客服的提示下解决。

Enabling the .NET framework on your Windows device
1. Type Turn on Windows features on or off on the search tab of your Windows device.
2.  Click Open to open the wizard.
3. Windows Features on or off dialog box will appear now.
4. Scroll, locate and select .NET Framework 4.8 Advanced Services and .Net Framework 3.5 (includes 2.0 and 3.0) and enable it. Click the OK button. StrongVPN V1 users should select the latter.
5. Windows will search for the required files.
6. Once the search is completed. It will apply the changes and complete the requested changes.
