### ISSUE TITLE
PIA挂了，哪个老哥有客服联系邮箱

### ISSUE THREAD

**Issue by MainByElse** [vpncn/vpncn.github.io#223]

**Comment by XuZelin2001** [comment]
https://helpdesk.privateinternetaccess.com/new-ticket  在这一页写ticket，就会有客服联系你。
最近PIA是不好用，客服也表示在修复中。目前谷歌插件还能用，英美服务器效果较好

**Comment by XuZelin2001** [comment]
或者直接打开官网，右下角点开联系在线客服

**Comment by XuZelin2001** [comment]
support@privateinternetaccess.com

**Comment by XuZelin2001** [comment]
问题是客服之前就回复说遇到问题了，正在修复，短期恐怕用不了

**Comment by MainByElse** [comment]
@XuZelin2001 好的，感谢老哥
