### ISSUE TITLE
win10安装strongVPN的精简版失败

### ISSUE THREAD

**Issue by nukupanda** [vpncn/vpncn.github.io#23]
需要依赖.NET Framework 2.0 Service Pack 2, win10都像不能装这个东西了

**Comment by nukupanda** [comment]
问题已经解决了，我再重装一次精准版它就可以了，虽然不知道什么原因。
问了支持人员，还需要做一个这样的设置：
Its a known issue from CH, Please change the DNS for your _main_ (but not VPN) network connection (normally it's ethernet or wireless):

1. Go into "Control Panel" > "Network and Sharing Center" > "Change adapter settings".
2. Right click on the "Local Area Connection" (wireless or broadband if you using one), choose "Properties".
3. Click the "Networking" tab.
4. Select "Internet Protocol (TCP/IPv4)".
5. Click "Properties" button.
6. Select "Use the following DNS server addresses:" and put the following numbers in:
8.8.8.8
8.8.4.4
7. Click "OK" and uncheck "Internet Protocol (TCP/IPv6)".
Then try to login once again please

**Comment by canty007** [comment]
我也碰到这个问题了，在wen10的“启用和关闭windows功能”中，把下面这项安装了就行。
![image](https://user-images.githubusercontent.com/21113894/164878245-7755a847-4629-4728-ad66-f060a6556875.png)

若无法安装，可以检查是否关闭了windows的自动更新。
