### ISSUE TITLE
感谢您的介绍和建议，我想了解一下标题中的 老王VPN

### ISSUE THREAD

**Issue by pao-ying** [vpncn/vpncn.github.io#24]
由于现在国家对VPN的管理更加严格了，像老王VPN这种Google Play上免费挂着的VPN，使用的时候安全性还能得以保证嘛？我指的安全性是会不会被国家查处，因为有很多人使用了野路子的VPN然后并不安全。
[https://play.google.com/store/apps/details?id=com.sticktoit](url)

**Comment by vpncn** [comment]
如果有访问敏感网页、涉及隐私信息，或是在手机上使用，尽量避免使用老王VPN这种软件，因为老王VPN被怀疑是钓鱼的，已经有人在手机上使用被请喝茶了，目前一般都是使用这种野路子VPN翻车的。这种翻墙软件我是不会使用的，测试都不敢。当然如果只是上网查查学习资料，不涉及账号登录，可以在电脑上使用。手机上隐私信息太多，不建议安装此类免费翻墙软件。
最好是使用[国外知名的VPN服务](https://github.com/vpncn/vpncn.github.io)，虽然有时会被封锁，但一年中绝大部分时间都是可以连接的，最重要的是安全，不泄漏隐私信息。

**Comment by pao-ying** [comment]
好的，谢谢答主的热心回答。
