### ISSUE TITLE
一个问题，strongVPN是全局代理吗？

### ISSUE THREAD

**Issue by kolarsullen** [vpncn/vpncn.github.io#26]
它是怎么判断这个地址是需要代理或是直连的？
目前的状况，我上steam它的加载速度明显变慢，是代理加载的，上正常网站似乎也有这个现象，所以说它是全程代理的吗？那不用的时候就得关掉了，但是考虑到它这个非常慢的连接速度，一直这样手动切换真的怪麻烦的……

**Comment by vpncn** [comment]
StrongVPN是全局代理，访问服务器设在国内的网站会变慢，目前还没有分流设置，解决办法是连接与地理位置较近的服务器（如韩国TCP协议），速度会快不少，或者在访问国内网站资源时关掉。
