### ISSUE TITLE
推荐一个我这边常用的一个VPN，可以试下

### ISSUE THREAD

**Issue by SirlSun** [vpncn/vpncn.github.io#271]
快连VPN：https://bitbucket.org/letsgogo/letsgogo_11/src/master/
备用链接：https://github.com/LetsGo666/LetsGo_2

安装后打开可以先到填写推荐人ID：76352258，能得3天会员，试下效果

**Comment by Biyougong831** [comment]
快连不是正规VPN，就是个套壳机场。用的SS线路，而且还限速。另外快连有被抓的记录。
哪怕用个机场都比快连强

**Comment by SirlSun** [comment]
> 而且还限速。另外快连有被抓的记录。 哪怕用个机场都比快连强

这个倒没考虑，后续可以弄下。不过现在这个VPN用着还可以，3个月一充就好，主要是啥都不用配置，直接用比较容易
