### ISSUE TITLE
最近是不是全部不能上了？

### ISSUE THREAD

**Issue by hannyu** [vpncn/vpncn.github.io#33]
StrongVPN 、 NordVPN 都连不上。

**Comment by vpncn** [comment]
最近又开始新一轮封锁了，26号开始的。
StrongVPN我刚试了一下，很稳，能上。电信网络，用的StrongVPN的精简版（文中有下载链接，也可找客服获取），试了Singapore、Tokyo和Seoul三个节点都可以一次连接成功。使用OpenVPN协议，如果UDP连不上，就用TCP，反之亦然。
NordVPN目前大部分节点不能客户端直连，要找客服获取服务器地址，手动配置翻墙。

**Comment by hannyu** [comment]
试了下 你说的这三个节点，都不行，UDP/TCP都不行。郁闷啊。太难了。

**Comment by vpncn** [comment]
是用的精简版吗？什么网络？

**Comment by vpncn** [comment]
![2020-10-28_161502](https://user-images.githubusercontent.com/60838758/97412466-94327900-193c-11eb-8b62-03dcbf891783.png)
刚刚试的

**Comment by Bravolis** [comment]
可以找客服要中国地区使用的版本，就是上面这个，这些天一直都能用。
