### ISSUE TITLE
为什么StongVPN我登不上去？

### ISSUE THREAD

**Issue by chaos0731wp** [vpncn/vpncn.github.io#34]
我刚刚付费并注册了STONGVPN账号，官方网站我登的上去，但用精简版客户端登录的时候客户端弹出了我的账户不可用这个窗口

**Comment by vpncn** [comment]
如果登录显示账号不可用，可能是支付过程出现了问题，需要登录官网用户后台确认支付，点击“Billing Area”，然后点击最右边的Invoices，看到自己选择的套餐是否显示为unpaid，点击unpaid，然后在打开的页面选择付款方式，并进行支付。

详细信息见文中"[如何购买StrongVPN](https://github.com/vpncn/vpncn.github.io#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96strongvpn)"

**Comment by chaos0731wp** [comment]
显示的是我已经付款了，但还是没用，登不上去，会弹出No Avaliable account 的窗口

**Comment by vpncn** [comment]
应该是账号信息有误，输入你注册Email收到的用户名和密码。如果还是不行咨询官网的在线客服。
