### ISSUE TITLE
辛苦了，能否看看lets vpn  

### ISSUE THREAD

**Issue by nickyoung22** [vpncn/vpncn.github.io#35]
能否看看lets vpn  我用了一年了 感觉蛮不错啊  敏感时期也是拉满  但奇怪很少有人提  我也犹豫要不要再换一个梯子

**Comment by vpncn** [comment]
lets vpn就是那个快连VPN吧，国产的，也许目前使用还不错，但上了黑名单，安全性可能存疑，使用这款要小心，不看敏感内容应该还好。
![2020-10-29_074235](https://user-images.githubusercontent.com/60838758/97508791-7ce6a080-19bb-11eb-949d-7b65f739266a.png)
