### ISSUE TITLE
这个lets vpn大佬看看怎么样

### ISSUE THREAD

**Issue by nickyoung22** [vpncn/vpncn.github.io#36]
我用了快一年  大概没啥问题  敏感时期还很稳...  但是很少听人推荐   是不是钓鱼的啊...   一个月算下来25了  其他的软件的价格也都差不多吗

**Comment by vpncn** [comment]
之前已经回复过你了：
lets vpn就是那个快连VPN吧，国产的，也许目前使用还不错，但上了黑名单，是不是钓鱼不清楚，安全性可能存疑，使用这款要小心，不看敏感内容应该还好。

截图：
![2020-10-29_074235](https://www.safewebcn.com/img/letsvpn-blacklist.png)

买一年大部分差不多都是这个价格。
