### ISSUE TITLE
关于StrongVPN的疑问

### ISSUE THREAD

**Issue by Xianrlingr** [vpncn/vpncn.github.io#39]
您好，我已经注册了账号，但是在登陆时一直提示错误，无法登录，请问是什么导致的？

**Comment by vpncn** [comment]
如果在StrongVPN官网下载的标准版客户端登陆异常，可以使用精简版V1 App，文中有下载地址。
也可以去官网的右下角的在线窗口咨询技术客服“Technical Support”，因为有些是本地DNS没有设置好。
