### ISSUE TITLE
hosts绑定

### ISSUE THREAD

**Issue by Emma-uestc** [vpncn/vpncn.github.io#4]
expressVPN  is a little more expensive hosts for me,想着用strongVPN，看你介绍需要使用官方给的hosts文件，hosts绑定就是一些域名绑定，如果我用strongVPN的话，把它给我的hosts中文件中的域名绑定内容放到我自己的hosts文件内也是可以的吧，我自己工作需要，本地hosts文件设置了一些域名绑定，自己的一定要用

**Comment by vpncn** [comment]
本文的hosts绑定只是当官网被挡在墙外时，在访问官网、购买和下载客户端时用的，用完就可以删除，或者用以前的hosts也可以，不影响客户端app的登陆和连接。
域名绑定内容添加到到你自己的hosts文件内也可以，不影响你原来的设置。

**Comment by Emma-uestc** [comment]
> 本文的hosts绑定只是当官网被挡在墙外时，在访问官网、购买和下载客户端时用的，用完就可以删除，或者用以前的hosts也可以，不影响客户端app的登陆和连接。
> 域名绑定内容添加到到你自己的hosts文件内也可以，不影响你原来的设置。

I see.我看了hosts文件，绑定的域名是strongvpn的官网域名，是为了解析到IP，这样的话，我不需要绑定，

**Comment by Emma-uestc** [comment]
请问，你最近strongVPN的连接情况怎么样呢，我的有几种情况，1.连接不上；2.连接上，无法访问Google，mainland的网站也无法访问了；3.刚连接上可以访问，过一分钟左右就无法访问了，内外都是；4.我的网络连接状态变成没有连接到网络。每次找客服，按照tech support说的方法操作，也只能work一段时间，或许都不到3小时，我通常会在两个地点使用电脑

**Comment by vpncn** [comment]
我刚才登陆了一下Tokyo和美国San Francisco节点，连接使用正常。Google和国内网站都能正常访问。

另外说一下，并不是所以的节点都能连接成功，但能连的节点还是不少的。

我在电脑上面的连接协议是使用的Open VPN（UDP），电信网络。不知你是怎样设置的？

网络连接状态变成没有连接到网络是打开了Kill Switch功能，这是避免断开VPN时信息泄露，这个功能可以关掉。

**Comment by Emma-uestc** [comment]
> 我刚才登陆了一下Tokyo和美国San Francisco节点，连接使用正常。Google和国内网站都能正常访问。
> 
> 另外说一下，并不是所以的节点都能连接成功，但能连的节点还是不少的。
> 
> 我在电脑上面的连接协议是使用的Open VPN（UDP），电信网络。不知你是怎样设置的？
> 
> 网络连接状态变成没有连接到网络是打开了Kill Switch功能，这是避免断开VPN时信息泄露，这个功能可以关掉。

我手机上一直是正常使用的，但是电脑上经常连接不上，或连接上无法工作(访问google等）每次跟客服沟通都花费数小时，当时解决了问题，过一段时间(甚至是一小时后）又不行了，就像昨天晚上用着好好的，过了一段时间就不能用了，还有个问题就是有时候连接上StrongVPN后，我的网络就会断掉，每次跟客服沟通，客服会让我一次次尝试他提供的方法。。。花费好久时间，真的太费时间了，你没有遇到过这些问题吗？

**Comment by vpncn** [comment]
有时过了一段时间不能用了应该是墙的检测机制检测到了，会限制数据传输，一般要等一段时间或者直接断开重连，这个我用的vpn或多或少都会有这个问题，敏感期更明显，平时还好。
不明白你的网络断掉是wifi断了还是说连接上不能访问网站？我这边倒是没有你说的这个情况。
