### ISSUE TITLE
Strong客户端精简版 如何开启openvpn

### ISSUE THREAD

**Issue by CrazyReason** [vpncn/vpncn.github.io#41]
如题，我好像只能使用这pptp这几种方式
![image](https://user-images.githubusercontent.com/22207324/99391234-dd129780-2914-11eb-9a3b-177938e98589.png)

**Comment by CrazyReason** [comment]
就算我设置 protocol preference这个为open vpn连接时，也不能选择open vpn

**Comment by vpncn** [comment]
点击Change Location看看能不能选择。
另外查看你的账户页面后台的VPN Accounts里面有没有OpenVPN，如果没看到去官网右下角找技术客服帮你开启OpenVPN Account.

**Comment by vpncn** [comment]
咨询了客服，这种情况需要开启legacy OpenVPN Account。

我在文章中更新了[使用提示](https://github.com/vpncn/vpncn.github.io#%E4%BD%BF%E7%94%A8%E5%BB%BA%E8%AE%AE)，可以在文中查看。

**Comment by CrazyReason** [comment]
已经找技术客服解决了，不过他帮忙开启OPENVPN权限后，客户端必须要重新登录才有效，否则会出现一个一直连接不上的错误，好像是跟openvpn与 pptp等协议不能共存。
