### ISSUE TITLE
30天包退

### ISSUE THREAD

**Issue by Kiwamm** [vpncn/vpncn.github.io#43]
你好，30天包退服务是无理由退货吗

**Comment by Kiwamm** [comment]
我个人感觉那个云盘好像没啥用诶，国内好多云盘注册都送几T的存储容量

**Comment by vpncn** [comment]
网站是这么说的，30天内可以退款。我测试退款一般试下速度和哪些节点可用，过几天退款也挺顺利，钱是原路返回。
如果用得多，而且只买了一个月，一个月快到期的时候申请退，这种情况就不知道能不能退了。

**Comment by Kiwamm** [comment]
哦哦，谢谢了
