### ISSUE TITLE
StrongVPN 普通版很难连上

### ISSUE THREAD

**Issue by crabloveloli** [vpncn/vpncn.github.io#44]
如题，mac和android的普通版都试了，各个协议也试过了，WireGuard协议不一定能连上，有时候显示连上了，但是google打不开，普通版的OpenVPN协议很难连上。
现在连接最稳定的还是简化版的OpenVPN协议，但是速度有点一言难尽，连接东京301，speedtest显示延迟260ms左右，下载0.4M，上传0.6M...(>_<)，不知道怎么办才好了，看Nord的评价也是不高，难道真的要退了买ExpressVPN...(T.T)
另附客服给的android的简化版链接，因为看到介绍里木有...(:-)
https://mirror1.reliablehosting.com/android/1.7.0.apk

**Comment by vpncn** [comment]
普通版的目前还没更新线路，很多线路连不上。现在还是使用简化版StrongVPN 的OpenVPN协议进行连接，StrongVPN没有做过speedtest的速度优化，实际速度一般比测试速度要好，东京节点确实比较慢，不过和使用时段、网络运营商有关系，上次我下午用移动4g连速度还不错。
现在亚洲的节点我用的最多的是韩国首尔，欧洲的是德国法兰克福，这两个速度在我这边还不错，美国节点很少用。

**Comment by crabloveloli** [comment]
多谢，不过还是弃坑算了，先用蓝灯凑合着，虽然蓝灯有时候也坑，付费版连接率有时候还比不过免费版，不过连上了速度比现在用Strong要快一些...我得考虑下试试Nord还是Express看看(>_<)

**Comment by NaughtyHotpot** [comment]
我ios遇到了同样的问题，WireGuard协议不一定能连上，有时候显示连上了，但是google打不开
楼主有没有什么建议
mac端用精简版可以连但是速度一般般😂

**Comment by crabloveloli** [comment]
> 我ios遇到了同样的问题，WireGuard协议不一定能连上，有时候显示连上了，但是google打不开
> 楼主有没有什么建议
> mac端用精简版可以连但是速度一般般😂

一定要用的话，只能找客服要简化版，不清楚ios有没有，你得自己问问...我自己google查了一下，strong的问题也是现在大多数VPN的问题：防火墙升级了。我查到大概从十月底开始，strong的标准版直连就基本上死掉了，其它的nord，pure也好不到哪里去。我估摸着短时间内恢复的可能不大，所以把strong退掉了，现在买了express，推荐的4个服务器偶尔也会出现自动重试几次也连接不上的情况，但多试几次还是可以连，速度也还可以接受，至少720P没什么卡顿的情况

**Comment by NaughtyHotpot** [comment]
> > 我ios遇到了同样的问题，WireGuard协议不一定能连上，有时候显示连上了，但是google打不开
> > 楼主有没有什么建议
> > mac端用精简版可以连但是速度一般般😂
> 
> 一定要用的话，只能找客服要简化版，不清楚ios有没有，你得自己问问...我自己google查了一下，strong的问题也是现在大多数VPN的问题：防火墙升级了。我查到大概从十月底开始，strong的标准版直连就基本上死掉了，其它的nord，pure也好不到哪里去。我估摸着短时间内恢复的可能不大，所以把strong退掉了，现在买了express，推荐的4个服务器偶尔也会出现自动重试几次也连接不上的情况，但多试几次还是可以连，速度也还可以接受，至少720P没什么卡顿的情况

嗯，感谢。
你们购买VPN是按月买的吗？ 现在Express买15个月半价，但是又担心之后会不会挂掉

**Comment by NaughtyHotpot** [comment]
strong vpn真是退款神速，老实讲strong vpn性价比还是很高的，几乎只要express三分之一的价格，在pc上网速是可以接受的（前提是你自己的宽带本来就好）只是现在在iOS上没用

**Comment by crabloveloli** [comment]
> > > 我ios遇到了同样的问题，WireGuard协议不一定能连上，有时候显示连上了，但是google打不开
> > > 楼主有没有什么建议
> > > mac端用精简版可以连但是速度一般般😂
> > 
> > 
> > 一定要用的话，只能找客服要简化版，不清楚ios有没有，你得自己问问...我自己google查了一下，strong的问题也是现在大多数VPN的问题：防火墙升级了。我查到大概从十月底开始，strong的标准版直连就基本上死掉了，其它的nord，pure也好不到哪里去。我估摸着短时间内恢复的可能不大，所以把strong退掉了，现在买了express，推荐的4个服务器偶尔也会出现自动重试几次也连接不上的情况，但多试几次还是可以连，速度也还可以接受，至少720P没什么卡顿的情况
> 
> 嗯，感谢。
> 你们购买VPN是按月买的吗？ 现在Express买15个月半价，但是又担心之后会不会挂掉

买了一年，送三个月，整体上Express还是更好一些，不过确实是贵多了

**Comment by fooSynaptic** [comment]
@crabloveloli 老哥你在哪里退款的，我怎么找不到。。。

**Comment by crabloveloli** [comment]
> @crabloveloli 老哥你在哪里退款的，我怎么找不到。。。

VPN Accounts下的第二个选项，取消订单，然后一通选，填个问卷，提交，等两三天就应该可以看到退款了
