### ISSUE TITLE
ExpressVPN 的优惠链接挂了

### ISSUE THREAD

**Issue by crabloveloli** [vpncn/vpncn.github.io#45]
如题，打不开了...前两周还可以通过优惠链接打开，现在只能直接手动打开官网。直接打开官网的折扣是99.5刀15个月，不知道跟优惠链接有差异没？
蓝灯那货越来越坑了，2年+3个月也是差不多要100刀，到期后肯定是不续了

**Comment by vpncn** [comment]
15个月就是一年送三个月，和我买的一样。

**Comment by crabloveloli** [comment]
了解了，多谢～
