### ISSUE TITLE
为什么我用ExpressVPN速度非常慢啊？

### ISSUE THREAD

**Issue by SuhaylZhao** [vpncn/vpncn.github.io#47]
刚买了一个月的ExpressVPN，速度非常慢，几乎难以忍受了。放在同事的电脑上用也一样。而且无法智能跳过国内的网站，使用体验真不如小众的VPN，但是小众VPN会跑路，亲历已经跑了两个了。太难了。

**Comment by SuhaylZhao** [comment]
![image](https://user-images.githubusercontent.com/3676296/101139375-6bdd1f00-364c-11eb-9a2f-5364e9b9de10.png)
基本上就是这样，点一下connect都要等半天才能连上，连上了速度也是非常慢。。。。

**Comment by vpncn** [comment]
这个自带的speedtest没什么用的，通的不一定能连，不通不一定连不上。
建议连接Los Angeles -5和新加坡Marina Bay节点，hk-4节点在有些地方是所有节点中最慢的。

**Comment by vpncn** [comment]
另外，访问国内的网站可以split tunneling设置进行分流，指定浏览器使用本地网络访问国内网站。
