### ISSUE TITLE
。。。完犊子，刚买完线路全都连不上，bestavaliable一直在试，要不要退款啊 买的是strongVPN

### ISSUE THREAD

**Issue by fooSynaptic** [vpncn/vpncn.github.io#51]

**Comment by vpncn** [comment]
认真看文章，文中有说明。如果连不上的话找客服要简化版客户端，用OpenVPN协议连接，很多节点可以正常使用。

**Comment by vpncn** [comment]
退款可以找在线客服直接退。很快就到了

**Comment by fooSynaptic** [comment]
> 认真看文章，文中有说明。如果连不上的话找客服要简化版客户端，用OpenVPN协议连接，很多节点可以正常使用。

最后确实是要退款客服扔给我一个客户端，老哥你给的那个链接没用，是不是更新一下
