### ISSUE TITLE
非常感谢推荐，想请教下Split Tunneling的问题。

### ISSUE THREAD

**Issue by Claire-kuzu** [vpncn/vpncn.github.io#52]
推荐里有写到可以通过不同浏览器来设置分别走不同流量，想请问是如何设置的。strongvpn windows版本好像没有这个功能，是插件么?安卓v1版有可能分应用么？麻烦了，谢谢。

**Comment by vpncn** [comment]
目前Split Tunneling是ExpressVPN的功能，strongvpn目前还没有分流功能。只能通过连接与中国地理位置较近的线路（比如韩国）来兼顾访问国内网站和上外网，访问国内网站速度肯定还是比不上国内的本地网络。
