### ISSUE TITLE
关于Strong VPN的购买问题

### ISSUE THREAD

**Issue by munpf** [vpncn/vpncn.github.io#53]
你好，我在购买了Strong VPN后，发来的邮件显示我这个是有50%的折扣，而且下一次续费就是正常价格了。
所以我就是想问一下他这个续费是指我到时候自己去续费还是会自动续费，虽然我从支付宝的自动付款那里没有找到这个支付选项，但是他这个说法总让我感觉像是会自动续费一样，所以想确认一下。

**Comment by vpncn** [comment]
只有PayPal付款有自动续费（可取消），支付宝不会自动续，要自己去续费。

**Comment by munpf** [comment]
多谢
