### ISSUE TITLE
关于StrongVPN连接问题

### ISSUE THREAD

**Issue by wsyw112233** [vpncn/vpncn.github.io#54]
最近使用StrongVPN 白天基本都能稳定连接，一到晚上18点开始 要么无法连接要么连接后也无法访问网络，然后本地官网也很难打开，请问这是他们服务器的问题吗？

**Comment by vpncn** [comment]
如果本地官网也难打开，可能是国际网络线路堵塞加上墙的干扰，另外也有线路的问题，比如我们这边移动网络普遍比电信要慢。

由于干扰，有时如果连接了还是无法访问网络，断开重连一般就好了，也可以服务器线路切换一下，我晚上用新加坡、日本线路比较慢，韩国和欧洲的几个节点速度快一些。

**Comment by wsyw112233** [comment]
> 如果本地官网也难打开，可能是国际网络线路堵塞加上墙的干扰，另外也有线路的问题，比如我们这边移动网络普遍比电信要慢。
> 
> 由于干扰，有时如果连接了还是无法访问网络，断开重连一般就好了，也可以服务器线路切换一下，我晚上用新加坡、日本线路比较慢，韩国和欧洲的几个节点速度快一些。
