### ISSUE TITLE
StrongVPN iOS手机端用不了啊

### ISSUE THREAD

**Issue by MourinhoLove** [vpncn/vpncn.github.io#56]
IP Address显示栏那边 一直都是Loding

**Comment by vpncn** [comment]
StrongVPN iOS端还没恢复直连，找客服要备用连接方案，或者用[ExpressVPN](https://linkv.org/express/)，这款iOS端挺稳。StrongVPN在一个月之内是可以退的。

**Comment by MourinhoLove** [comment]
好的
