### ISSUE TITLE
已经购买strongvpn，但是官网一直进不去

### ISSUE THREAD

**Issue by nellahx** [vpncn/vpncn.github.io#60]
付款成功之后，官网一直join in 不了。无奈之下，只好注册GitHub的账号。我是用163邮箱注册的，需要验证那一步，电脑端打不开网易邮箱了，显示什么防火墙/断网什么的。我也不懂这些东西，以为是hosts文件的原因，又把hosts文件换成了原来的，还是没有办法登陆邮箱，也登陆不上官网。好在qq邮箱可以使用，所以还能够评论。为什么官网登不上呢？刚开始操作的时候，一切都还挺顺利的，就是加载的慢了一些。但是已经付费了，如果官网一直登陆不上的话，也没办法使用，没办法退款。所以，能麻烦你帮我解答一下问题吗？我真的很小心操作了。。。但是又对电脑一窍不通。拜托了，谢谢你。

**Comment by nellahx** [comment]
如果方便的话，回复发到我的邮箱（nellahx@163.com）可以吗？我可以用手机查收，谢谢你。

**Comment by vpncn** [comment]
解决了吗？是不是电脑安装了360、电脑管家等国产杀毒软件被挡了？
