### ISSUE TITLE
有没有推荐国外连回中国的方法

### ISSUE THREAD

**Issue by willyyyyy1** [vpncn/vpncn.github.io#62]
有没有推荐国外连回中国的方法

**Comment by vpncn** [comment]
如果是在国外连中国的线路，[PureVPN](https://github.com/vpncn/vpncn.github.io#6-purevpn)可以，有中国的线路。

**Comment by willyyyyy1** [comment]
好的

**Comment by willyyyyy1** [comment]
> 如果是在国外连中国的线路，[PureVPN](https://github.com/vpncn/vpncn.github.io#6-purevpn)可以，有中国的线路。
好的 谢谢
