### ISSUE TITLE
StrongVPN 策略设置

### ISSUE THREAD

**Issue by caixiaomao** [vpncn/vpncn.github.io#64]
请问 StrongVPN 怎么设置访问策略，有些地址想直连，不想走vpn，找了好久没找到 😢

**Comment by caixiaomao** [comment]
或者能设置指定的地址走vpn

**Comment by vpncn** [comment]
StrongVPN目前是全局代理，应该没有这个功能

**Comment by caixiaomao** [comment]
> StrongVPN目前是全局代理，应该没有这个功能

哦哦 好的 谢谢啦
