### ISSUE TITLE
surfshark

### ISSUE THREAD

**Issue by fz112400** [vpncn/vpncn.github.io#67]
这个VPN怎么样呢？

**Comment by vpncn** [comment]
安全性倒是可以，可用性一般，之前断断续续使用过几次，可用率一般，感觉和Pure、ivacy差不多，就没有单独列上来了。

**Comment by fz112400** [comment]
emm......亲自试了下，surfshark手机端(安卓)能用，但是电脑端(windows和Linux)用不了，需要联系客服索要中国可用服务器的openvpn配置文件，配置openvpn来使用......
