### ISSUE TITLE
express最近不稳定的问题

### ISSUE THREAD

**Issue by XinyuZeng** [vpncn/vpncn.github.io#78]
感觉这几天express可用率，连接的稳定性以及速度都大大降低，联系客服没有给出什么实际解决方案，只让多换几个节点试试。这导致我经常要换节点或者protocol尝试，连上了还可能断，体验极差。请问朋友们有什么解决方案吗

**Comment by vpncn** [comment]
试一下Marina Bay和LA-5，我这边连着还可以。另外如果是在电脑上，切换L2TP协议试试。
