### ISSUE TITLE
strongVPN装了客服给的1.6.5可以connect但是上不了网

### ISSUE THREAD

**Issue by gaoming96** [vpncn/vpncn.github.io#83]
win10系统，使用了客服给的1.6.5版本，成功显示connect了，但是无论是外网还是baidu都打不开。
请问这是什么原因？
我把dns改成8.8.8.8，也改回来了，都试过还是不行。
谢谢！

附上客服的回复：
I would recommend to download and use the StrongVPN V1 client application from our website only, here is the link:
https://mirror2.reliablehosting.com/win/StrongVPN_Win_1.6.5.exe
This is the latest version that should work fine in China.
Also please delete the DNS from your network settings and restart your computer. Then try to connect the VPN again. I've changed your server to the one that is confirmed to work fine for users from China.

**Comment by vpncn** [comment]
1.断开重连，有时断开重新连接就好了。
2.电脑上是否装360、腾讯电脑管家等国产杀毒软件，这些软件可能会阻止VPN流量。

**Comment by gaoming96** [comment]
感谢回复。
奇怪了，我的确断开重连了，而且电脑没有装杀毒软件。
