### ISSUE TITLE
算是一个小安利

### ISSUE THREAD

**Issue by zhang2516** [vpncn/vpncn.github.io#84]
老哥，你可以看看iguge这个插件，免费的时候可以上google 和Google scholar，收费就基本都可以上了，比如油管p站啥的。缺点是只是个插件，在chorm和edge上有，优点是非常稳定加不贵(比express便宜太多了)，我从来没遇到过断流的情况，而且一连就连上，用了差不多一年了
老哥你看完之后把问题关了就行

**Comment by twy12689** [comment]
就是说只能在web中使用？APP无法代理?
