### ISSUE TITLE
Strong VPN有没有Linux的客户端

### ISSUE THREAD

**Issue by munpf** [vpncn/vpncn.github.io#85]
如题，看介绍里似乎没有提到linux的客户端，在官网也没有找到

**Comment by vpncn** [comment]
Strong VPN没有Linux的客户端，国内使用只能OpenVPN手动设置。

**Comment by munpf** [comment]
> Strong VPN没有Linux的客户端，国内使用只能OpenVPN手动设置。

好吧，既然没有那也没办法，多谢
