### ISSUE TITLE
Mac端，求帮助

### ISSUE THREAD

**Issue by jxy5969** [vpncn/vpncn.github.io#86]
在同一个网络下，windows的客户端可以连接，但是mac的不行，用的都是精简版客户端，不论怎么换节点都不行，一直都是正在连接

**Comment by vpncn** [comment]
我Mac是这样设置的，都能正常使用，点开Preferences（偏好）设置，协议选择OpenVPN（TCP）进行连接。
另外，连的时候点击客户端最下方的Diagnostics诊断查看一下。

**Comment by jxy5969** [comment]
> 我Mac是这样设置的，都能正常使用，点开Preferences（偏好）设置，协议选择OpenVPN（TCP）进行连接。
> 另外，连的时候点击客户端最下方的Diagnostics诊断查看一下。

我也是这样设置的，还是不行。一直都是正在连接。

**Comment by vpncn** [comment]
> > 我Mac是这样设置的，都能正常使用，点开Preferences（偏好）设置，协议选择OpenVPN（TCP）进行连接。
> > 另外，连的时候点击客户端最下方的Diagnostics诊断查看一下。
> 
> 我也是这样设置的，还是不行。一直都是正在连接。

我刚刚才连了的，一切正常。看看你的DNS设置，或者换个节点连接。
