### ISSUE TITLE
你好，Mac端求帮助，是速度的问题

### ISSUE THREAD

**Issue by wtyqer** [vpncn/vpncn.github.io#88]
设备：
北京电信100M
网关型号 ZXHN F650（GPON ONU）3.0【2.4G单频WI-FI】
路由器型号 360安全路由（主频1GHZ）【2.4G/5G双频WI-FI】

目前节点能连上3个，最快的是节点是 Japan-Yokohama
下面是测的三次的平均速度：
延迟：172ms
下载：6M
上传：20M

由于路由器的关系有下面两个频段可用：

1.本网的速度（5G频）：
延迟：18ms
下载：245M
上传：36M

2.本网的速度（2.5G频）：
延迟：17ms
下载：52M
上传：36M
 
看你测的下载速度都是几十兆，我的却只有个位数

**Comment by wtyqer** [comment]
看油管1080p根本播不动啊

**Comment by vpncn** [comment]
我这边速度最快的是韩国Seoul节点，你试试这个，另外我实测的TCP协议速度比UDP感觉快一些。
如果你那边速度一般，退了试试express，速度很快。这两个都可以退款的。
