### ISSUE TITLE
求助：StrongVPN v1.6.5 win10 用不了

### ISSUE THREAD

**Issue by Hosing2015** [vpncn/vpncn.github.io#93]
联系了技术支持，发的 windows 客户端 StrongVPN v1.6.5 还是用不了，安卓手机上可以用。特求助各位大佬。

**Comment by Hosing2015** [comment]
程序错误信息如下：ps: 客服已经开通过 open vpn account.
An error occured while trying to connect.  The error provided was: Sun Apr 11 22:08:30 2021 us=620028 AUTH: Received control message: AUTH_FAILED

**Comment by vpncn** [comment]
我的Windows系统可以用，v1.6.5版本的，使用OpenVPN TCP协议，很多节点都可以连。

**Comment by Hosing2015** [comment]
> 我的Windows系统可以用，v1.6.5版本的，使用OpenVPN TCP协议，很多节点都可以连。

可能我的系统版本太高，多谢回复！
