### ISSUE TITLE
strongvpn电脑上不起作用

### ISSUE THREAD

**Issue by backdoorxinghe** [vpncn/vpncn.github.io#94]
让客服开了OpenVPN account，用的V1 1.65特供版客户端，dns设置的8.8.8.8 8.8.8.4，用了scramble，期间反复重启，卸载重装尝试了几小时仍然不起任何作用。而安卓上连了同一个节点的V1客户端能正常用，到底什么导致的

**Comment by vpncn** [comment]
我这边没有设置DNS，默认自动获取。连接协议使用TCP成功率会高一些，在换其他节点试试，一般安卓能连的话电脑也能连，可能设置没有到位。
另外，把Strongvpn标准版的客户端先安装一下，有读者这样解决的。

**Comment by backdoorxinghe** [comment]
> 我这边没有设置DNS，默认自动获取。连接协议使用TCP成功率会高一些，在换其他节点试试，一般安卓能连的话电脑也能连，可能设置没有到位。
> 另外，把Strongvpn标准版的客户端先安装一下，有读者这样解决的。

**Comment by backdoorxinghe** [comment]
> 我这边没有设置DNS，默认自动获取。连接协议使用TCP成功率会高一些，在换其他节点试试，一般安卓能连的话电脑也能连，可能设置没有到位。
> 另外，把Strongvpn标准版的客户端先安装一下，有读者这样解决的。

我根据教程一开始就安装了标准版的客户端，连接协议也是tcp，节点更换了数个仍然没什么用
