### ISSUE TITLE
ExpressVPN Split Tunneling设置

### ISSUE THREAD

**Issue by woshitangjiang** [vpncn/vpncn.github.io#98]
大佬你的Split Tunneling设置怎么弄的，为什么我让火狐浏览器走本地流量后访问国内网站会更慢，比不使用Split Tunneling功能的访问速度更慢 @vpncn

**Comment by vpncn** [comment]
你看设置里面的Advanced选项，“Only use ExpressVPN DNS servers...”可能是只用ExpressVPN的DNS导致的。

**Comment by woshitanjiang** [comment]
好的，我试试。谢谢你的帮助


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月30日(周日) 晚上10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vpncn/vpncn.github.io] ExpressVPN Split Tunneling设置 (#98)




 
你看设置里面的Advanced选项，“Only use ExpressVPN DNS servers...”可能是只用ExpressVPN的DNS导致的。
 
&mdash;
